site_name: Nitrapi Documentation
theme: readthedocs
extra_css: [extra.css]
pages:
- Documentation:
  - About: 'index.md'
  - oAuth2: 'oauth.md'
- Resources:
  - Ping: 'resources/ping.md'
  - User: 'resources/user.md'
  - User SSH Keys: 'resources/user_ssh_keys.md'
  - Token: 'resources/token.md'
  - Services: 'resources/services.md'
  - Websocket: 'resources/websocket.md'
  - Webinterface: 'resources/webinterface.md'
  - Gameserver: 'resources/gameserver.md'
  - Cloud Server: 'resources/cloud_server.md'

- Order Resources:
  - Information: 'resources/order/information.md'
  - Payment: 'resources/order/payment.md'
  - Gameserver: 'resources/order/gameserver.md'
  - 'Teamspeak 3': 'resources/order/teamspeak3.md'
  - Webspace: 'resources/order/webspace.md'
  - Musicbot: 'resources/order/musicbot.md'
  - Ventrilo: 'resources/order/ventrilo.md'
  - Mumble: 'resources/order/mumble.md'
  - Bouncer: 'resources/order/bouncer.md'

- Cloud Server Resources:
  - Global: 'resources/cloud_servers/global.md'
  - Power Events: 'resources/cloud_servers/power_events.md'
  - Resources: 'resources/cloud_servers/resources.md'
  - Traffic: 'resources/cloud_servers/traffic.md'

- Gameserver Resources:
  - Global: 'resources/gameservers/global.md'
  - Settings: 'resources/gameservers/settings.md'
  - Tasks: 'resources/gameservers/tasks.md'
  - Game switching: 'resources/gameservers/game_switch.md'
  - File Server: 'resources/gameservers/file_server.md'
  - App Server: 'resources/gameservers/app_server.md'
  - Addons: 'resources/gameservers/addons.md'
  - Plugins: 'resources/gameservers/plugins.md'
  - Plugin System: 'resources/gameservers/plugin_system.md'
  - DDoS History: 'resources/gameservers/ddos.md'
  - 'Games specific':
    - Minecraft: 'resources/gameservers/games/minecraft.md'
    - 'Minecraft Backups': 'resources/gameservers/games/minecraft_backups.md'

- Voiceserver Resources:
  - Global: 'resources/voiceservers/global.md'
  - Backup: 'resources/voiceservers/backup.md'
site_author: marbis GmbH
